In [1]:
import pandas as pd

# Carga del dataset

In [4]:
train_df = pd.read_csv(r'dataset/train.csv')
train_df

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15759244,Boone,687.0,Germany,Male,44,8,95368.14,2.0,1.0,1,1787.85,0
1,15725997,She,660.0,France,Female,35,6,100768.77,1.0,1.0,0,19199.61,0
2,15724296,Kerr,684.0,Spain,Male,41,2,119782.72,2.0,0.0,0,120284.67,0
3,15636820,Loggia,725.0,Germany,Male,40,8,104149.66,1.0,1.0,0,62027.90,0
4,15744529,Chiekwugo,510.0,France,Male,63,8,0.00,2.0,1.0,1,115291.86,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,15628303,Thurgood,738.0,Spain,Male,35,3,0.00,1.0,1.0,1,15650.73,0
7996,15699225,Pirozzi,757.0,France,Male,46,0,0.00,2.0,1.0,0,37460.05,0
7997,15612525,Preston,NaN,France,Female,57,1,NaN,1.0,0.0,0,131372.38,1
7998,15724321,Baresi,516.0,Germany,Female,47,9,128298.74,1.0,0.0,0,149614.17,1
7999,15578761,Cunningham,NaN,Spain,Female,42,6,129634.25,NaN,1.0,1,177683.02,1

In [6]:
X = train_df.drop(columns=['Exited'])
y = train_df['Exited']

In [7]:
X

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,15759244,Boone,687.0,Germany,Male,44,8,95368.14,2.0,1.0,1,1787.85
1,15725997,She,660.0,France,Female,35,6,100768.77,1.0,1.0,0,19199.61
2,15724296,Kerr,684.0,Spain,Male,41,2,119782.72,2.0,0.0,0,120284.67
3,15636820,Loggia,725.0,Germany,Male,40,8,104149.66,1.0,1.0,0,62027.90
4,15744529,Chiekwugo,510.0,France,Male,63,8,0.00,2.0,1.0,1,115291.86
...,...,...,...,...,...,...,...,...,...,...,...,...
7995,15628303,Thurgood,738.0,Spain,Male,35,3,0.00,1.0,1.0,1,15650.73
7996,15699225,Pirozzi,757.0,France,Male,46,0,0.00,2.0,1.0,0,37460.05
7997,15612525,Preston,NaN,France,Female,57,1,NaN,1.0,0.0,0,131372.38
7998,15724321,Baresi,516.0,Germany,Female,47,9,128298.74,1.0,0.0,0,149614.17
7999,15578761,Cunningham,NaN,Spain,Female,42,6,129634.25,NaN,1.0,1,177683.02

In [8]:
y

0       0
1       0
2       0
3       0
4       0
       ..
7995    0
7996    0
7997    1
7998    1
7999    1
Name: Exited, Length: 8000, dtype: int64

In [5]:
test_df = pd.read_csv(r'dataset/test.csv')
test_df

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,15764618,Tseng,815.0,Spain,Female,39,6,0.00,1.0,1.0,1,85167.88
1,15626385,George,714.0,Spain,Female,33,10,103121.33,2.0,1.0,1,49672.01
2,15687413,Sunderland,619.0,Spain,Female,38,6,0.00,2.0,1.0,1,117616.29
3,15759067,Bromby,537.0,Germany,Female,37,7,158411.95,4.0,1.0,1,117690.58
4,15614049,Hu,664.0,France,Male,55,8,0.00,2.0,1.0,1,139161.64
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,15572956,Steen,683.0,France,Male,36,5,115350.63,NaN,NaN,1,122305.91
1996,15714080,Goliwe,NaN,Germany,Female,40,2,NaN,2.0,1.0,0,NaN
1997,15637366,Su,505.0,Germany,Female,25,5,114268.85,2.0,1.0,1,126728.27
1998,15697625,Bevan,791.0,France,Male,37,2,163789.49,2.0,1.0,0,75832.53
1999,15653780,Kambinachi,621.0,France,Female,43,5,0.00,1.0,1.0,1,47578.45

# Análisis exploratorio

In [9]:
print("\nDimensiones del dataset:")
print(X.shape)

print("\nDistribución de la variable objetivo:")
print(y.value_counts().sort_index())

print("\nEstadísticas descriptivas:")
print(X.describe())

Dimensiones del dataset:
(8000, 12)

Distribución de la variable objetivo:
Exited
0    6370
1    1630
Name: count, dtype: int64

Estadísticas descriptivas:
         CustomerId  CreditScore          Age       Tenure        Balance  \
count  8.000000e+03  6359.000000  8000.000000  8000.000000    6385.000000
mean   1.569119e+07   661.235257    38.935000     5.013875   76929.669179
std    7.187227e+04    95.876126    10.381389     2.888810   62292.133487
min    1.556570e+07   350.000000    18.000000     0.000000       0.000000
25%    1.562896e+07   595.000000    32.000000     3.000000       0.000000
50%    1.569112e+07   664.000000    37.000000     5.000000   98009.130000
75%    1.575373e+07   729.000000    44.000000     8.000000  127660.460000
max    1.581569e+07   850.000000    92.000000    10.000000  250898.090000

       NumOfProducts    HasCrCard  IsActiveMember  EstimatedSalary
count    7024.000000  7625.000000     8000.000000      7168.000000
mean        1.539721     0.706623        0.513500    100057.165753
std         0.574125     0.455340        0.499849     57441.733108
min         1.000000     0.000000        0.000000        11.580000
25%         1.000000     0.000000        0.000000     51545.352500
50%         2.000000     1.000000        1.000000    100129.075000
75%         2.000000     1.000000        1.000000    149216.320000
max         4.000000     1.000000        1.000000    199992.480000